version: '3.5'
services:
  nodejs:
    build:
      context: .
    env_file: .env
    container_name: 'scratchpay-test-nodejs'
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
